version: '1.0'
services:
  web_api:
    build:
      context: ./src/
    container_name: web_api_application 
    ports:
      - "5000:80" 
    restart: on-failure  
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: hoop_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: student
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alex@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dbpass
  