version: '3.4'

services:
  hoophub.api:
    image: ${DOCKER_REGISTRY-}hoophubapi
    build:
      context: .
      dockerfile: API/HoopHub.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001" 
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: hoop_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: student
    volumes:
      - ./.containers/hoop_hub-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alex@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dbpass
   