version: '3.4'

services:
  hoophub.api:
    image: ${DOCKER_REGISTRY-}hoophubapi
    build:
      context: .
      dockerfile: API/HoopHub.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001" 
  hoop_hub.database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: hoop_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: student
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alex@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dbpass
   